version: '3'
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: search
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 100M
